-- database/schema.sql
CREATE TABLE iei_members (
    member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    role VARCHAR2(50), -- e.g., 'Chairman', 'Secretary'
    designation VARCHAR2(150), -- e.g., 'Retd. Chief Engineer'
    professional_message CLOB,
    image_url VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
